### ISSUE TITLE
meta-xenomai vs. meta-xenomai

### ISSUE THREAD

**Issue by jan-kiszka** [intel/meta-xenomai#2]
Does this build upon or otherwise relate to https://bitbucket.org/pficheux/meta-xenomai/? The latter is what people find when looking for Xenomai in https://layers.openembedded.org. Would be good to align both on the long run.

**Comment by finomeng** [comment]
Hi Jan, this meta layer is mostly for PI3. I will discuss with Florent and rename our meta layer first to avoid conflict.

**Comment by Pirouf** [comment]
Thanks Jan for your interest.

indeed we are aware of the precedence of OSS meta-xenomai from pficheux in OE registry. Yocto meta-intel maintainer Intel team will decide mid-term the most appropriate alignment with https://layers.openembedded.org.  In parallel, we might also look at aligning against meta-layers and recipes you maintain under https://gitlab.denx.de/Xenomai/xenomai-images. for Integration System for Automated Root (isar) filesystem generation. 

For now, this meta-layer aim to serve OT SW engineering stackholder needs resolving xenomai-stable and xenomai-dev out-of-tree integration on Intel base-platform BSPs released with Intel LTS/production kernel (ie. SoC-specific reference-point for OT), see pointer below:
- https://www.yoctoproject.org/software-overview/layers/bsps/
- https://github.com/intel/iotg-yocto-bsp-public/tree/e3900/master

Those BSPs are being referenced on a given lts-intel-stable commits-id, for example next meta-layer update will  add https://github.com/intel/linux-intel-lts/commits/4.19/base branch with reference-point lts2018-stable commit-id 950cf60b4bf6d8d6f4b1ecdebc4bc8993806ce02 to build & validate ipipe-4.19-split and xenomai 3.1-rcZ  dev on latest Yocto Poky Intel IoTG reference BSPs. 
(see illustration below) 
![2019-12-20_10h39_52](https://user-images.githubusercontent.com/19978468/71245482-13b2ed00-2315-11ea-971d-4accc68c1c35.png)

**Comment by finomeng** [comment]
just create new repo,  https://github.com/intel/meta-xenomai-intel
change to new name to avoid conflict.

**Comment by finomeng** [comment]
already move all code to https://github.com/intel/meta-xenomai-intel;
plan to clear this repo; but don't delete it, keep it as a place holder;
